services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB:   core_db
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core_pass
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: ../services/core_project/app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Django settings
      DJANGO_DEBUG:        "False"
      DJANGO_SECRET_KEY:   "replace-me-with-a-real-secret"
      ALLOWED_HOSTS:       "localhost,127.0.0.1"
      # Database settings
      POSTGRES_DB:         core_db
      POSTGRES_USER:       core_user
      DB_PASSWORD:         core_pass
      DB_HOST:             db
      DB_PORT:             "5432"
    depends_on:
      - db
    # If you want live code reload in dev, you can mount your local files:
    # volumes:
    #   - ../services/core_project/app:/app

volumes:
  db_data:
