# infrastructure/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB:   your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: ../services/core_project/app
      dockerfile: Dockerfile
    command: ["gunicorn", "core_project.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG:        "False"
      ALLOWED_HOSTS:       "localhost,127.0.0.1"
      POSTGRES_DB:         your_db_name
      POSTGRES_USER:       your_db_user
      DB_PASSWORD:         your_db_password
      DB_HOST:             db
      DB_PORT:             "5432"
    depends_on:
      - db

volumes:
  db_data:
