version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow:
    build:
      context: ../services/mlflow
      dockerfile: Dockerfile
    container_name: resit_mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlruns:/mlruns
    depends_on:
      - db


  inference:
    build: ../services/inference
    env_file: .env
    depends_on: [db]
    ports:
      - "8001:8000"

  training:
    build: ../services/training
    env_file: .env
    depends_on: [db, mlflow]
    ports:
      - "8002:8000"

  billing:
    build: ../services/billing
    env_file: .env
    depends_on: [db]
    ports:
      - "8003:8000"


  core:
    build:
      context: ../services/core_project
      dockerfile: Dockerfile
    container_name: core_backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ../services/core_project/app:/app

volumes:
  db_data:
  mlruns:
