name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ai-unit-tests:
    name: AI Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install AI dependencies
        run: |
          pip install --upgrade pip
          pip install -r services/training/requirements.txt
          pip install pytest
      - name: Run AI unit tests
        run: pytest tests/unit

  service-tests:
    name: Service Tests
    needs: ai-unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ inference, training, billing, users ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install service dependencies
        run: |
          pip install --upgrade pip
          pip install -r services/${{ matrix.service }}/requirements.txt
          pip install flake8 mypy
      - name: Lint service code
        run: flake8 services/${{ matrix.service }}
      - name: Type-check service code
        run: mypy services/${{ matrix.service }}
      - name: Run Django tests
        working-directory: services/${{ matrix.service }}/app
        run: python manage.py test
