name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v3

      # 2. Set up Python and cache pip
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4. (Optional) Pull & repro your DVC pipeline
      - name: Set up DVC & pull data
        run: |
          source .venv/bin/activate
          pip install dvc
          dvc pull
          dvc repro

      # 5. Run your tests
      - name: Run unit/integration tests
        run: |
          source .venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q

      # 6. Execute the notebook
      - name: Execute master notebook
        run: |
          source .venv/bin/activate
          pip install jupyter nbconvert
          jupyter nbconvert \
            --to html \
            --execute notebooks/master_notebook.ipynb \
            --output executed_notebook.html \
            --ExecutePreprocessor.timeout=600

      # 7. Upload the rendered notebook for review
      - name: Upload notebook artifact
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_notebook.html
